universe   = vanilla
getenv     = true
executable = /project/gravwav/admayol/master_project/lensed/run_1/run_1.sh
output = /data/gravwav/admayol/lensed/logs/run1.out
error = /data/gravwav/admayol/lensed/logs/run1.err
log = /data/gravwav/admayol/lensed/logs/run1.log
initialdir = /project/gravwav/admayol/master_project/lensed/run_1
notify_user = arnau.duran.m@gmail.com 
notification = Complete
arguments  = "-processid $(Process)"
request_memory = 64GB
request_cpus = 32
on_exit_remove = (ExitBySignal == False) || ((ExitBySignal == True) && (ExitSignal != 11))
accounting_group = gravwav
+UseOS = "el9"
+JobCategory = "long"
queue 1
